
-- Create tables

CREATE TABLE CHANNEL(
	ID INTEGER NOT NULL, 
	"NAME" VARCHAR(255) NOT NULL UNIQUE,
	IS_PUBLIC BOOLEAN NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE CHAT_USER (
	ID INTEGER NOT NULL, 
	"NAME" VARCHAR(255) NOT NULL UNIQUE, 
	PASSWORD VARCHAR(255) NOT NULL, 
	IS_MODERATOR BOOLEAN NOT NULL, 
	PRIMARY KEY (ID)
);

CREATE TABLE CHANNEL_USER(
	USER_ID INTEGER NOT NULL,
	CHANNEL_ID INTEGER NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
	FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL (ID),
	PRIMARY KEY (USER_ID, CHANNEL_ID)
);

CREATE TABLE MESSAGE (
	ID INTEGER NOT NULL, 
	CONTENT VARCHAR(2000), 
	"TIMESTAMP" TIMESTAMP NOT NULL, 
	CHANNEL_ID INTEGER NOT NULL, 
	USER_ID INTEGER NOT NULL, 
	FOREIGN KEY (USER_ID) REFERENCES CHAT_USER (ID),
	FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNEL (ID),
	PRIMARY KEY (ID)
);
